---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
geometry: margin=1in

title: "CURRICULUM VITAE"
author: Pablo M. Guzm&aacute;n Lizardo

jobtitle: "PhD Candidate in Political Economics at the Stanford Graduate School of Business"
address: "10 Comstock Circle, 94305, Stanford, CA, USA"
fontawesome: yes
email: pablo.guzmanlizardo@stanford.edu
#github: pguzmanlizardo
#osf: "Enter 5 digit osf string here"
#phone: "+1 438 928 4902"
# web: guinness.com
updated: no

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue

#bibliography: "publications.bib"
---

# EDUCATION

\vspace{-0.4cm}
\rule{\textwidth}{1pt}

**Stanford Graduate School of Business** *PhD Candidate in Political Economics* \hfill 2021 - Present    
*Fields*: Political Economics, Public Economics, Development Economics  
*Committee*: Katherine Casey (principal advisor), Caroline Hoxby, Beatriz Magaloni-Kerpel, Juan Carlos Su&aacute;rez Serrato, Gregory Martin

**McGill University, ** *B.A. Honours Economics, B.A. Honours Political Science, Minor Concentration in Mathematics* \hfill 2017-2021    

# RESEARCH PAPERS AND WORK IN PROGRESS

\vspace{-0.4cm}
\rule{\textwidth}{1pt}

## **JOB MARKET PAPER**

**The Path From Low to High Fiscal Capacity (\underline{Job Market Paper})**    
*Co-authored with Wilson Prichard and Niccol&ograve; Meriggi*   
We implement an RCT involving over 6000 property owners to evaluate different strategies to increase tax compliance amidst a broader property tax reform in Kenema, Sierra Leone. We collaborated with the Kenema City Council to introduce a system of communications and a tax court to increase the transparency and accountability of traditional tax enforcement procedures. We also collaborate with religious leaders to motivate tax compliance and provide a rationale for taxation. The experiment shows that receiving enforcement increased compliance by 53.4 p.p., while the sensitization treatment increases compliance by 4.9 p.p. Using a recentered-IV approach, we find evidence of spatial spillovers. Baseline and midline surveys show substantive increases in pro-tax attitudes among all property owners in the city and no evidence of a backlash effect from enforcement. 

## **WORK IN PROGRESS**
**Impact of Militarized Policing in Dominican Republic**  
I build a novel panel dataset that tracks all mixed, police-military, patrolling interventions in Dominican Republic; and all crime incidents that occurred in a particular locality during the period between January 1st, 2023, and June 30th, 2023. I find that these mixed patrols lead to a decrease of 0.011 units of crime during the week after an intervention. I fail to find evidence of spillover effects resulting from the mixed-patrolling interventions. 


# RESEARCH EXPERIENCE

\vspace{-0.4cm}
\rule{\textwidth}{1pt}


**Stanford Graduate School of Business**, *Graduate Research Assistant* \hfill 2022-2024      
Worked under the supervision of Professor Katherine Casey. Responsibilities includes research and operational support for the Candidate Selection project in Sierra Leone. 

**Rotman School of Management at University of Toronto**, *Research Assistant* \hfill 2018-2021   
Worked under the supervision of Professor Laura Doering. Responsibilities include research, data analysis and manipulation using Stata. 

# TEACHING EXPERIENCE

\vspace{-0.4cm}
\rule{\textwidth}{1pt}

**Stanford Graduate School of Business**, *Course Assistant* \hfill Winter 2025   
POLECON 231: Strategy Beyond Markets. Assisted with leading class activities, grading assignments, and providing support to MBA students.

# AWARDS AND RESEARCH GRANTS

\vspace{-0.4cm}
\rule{\textwidth}{1pt}

**International Growth Centre Full Research Grant**, *&pound;75,000*   \hfill 2024      
**Local Government Revenue Initiative Grant**, *&euro;188,664*   \hfill 2024      
**Local Government Revenue Initiative Grant**, *USD &dollar;51,165*   \hfill 2024      
**International Growth Centre Small Projects Fund**, *&pound;19,000*   \hfill 2024      
**Charles William Snyder Memorial Scholarship** \hfill 2020   
**McGill University Faculty of Arts' Dean's Honour List** \hfill 2018-2020   

# LEADERSHIP AND COMMUNITY SERVICE

\vspace{-0.4cm}
\rule{\textwidth}{1pt}

**Conference Co-Organizer,** *2024 DevPEC* \hfill April 2024    
Co-organized the 2024 edition of the student-led Development and Political Economics Conference (DevPEC). The conference is a collaboration between Stanford University's Economics Department and the University of Berkeley's Economics Department. Co-organized with Silvia Farina, Eva Davoine, and Kyra Frye. 


# SKILLS AND INTERESTS

\vspace{-0.4cm}
\rule{\textwidth}{1pt}

**Languages:** English (Bilingual), Spanish (Native), French (Advanced), Portuguese (Intermediate), Sierra Leonean Krio (Beginner).

**Statistical packages and programming languages:** R, Python, Stata, SPSS, SQL.

**Survey Implementation:** SurveyCTO.

**Communication and collaboration:** RMarkdown, LaTex, Git.

```{r eval=FALSE, include=FALSE}
# Run the code below to knit the file
rmarkdown::render(input = "cv_general.Rmd",
                  output_file = "cv_general.pdf",
                  output_dir = "..")

```

